/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scrap.heap.refactor;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

import scrap.heap.refactor.dto.BalloonDto;
import scrap.heap.refactor.dto.CakeDto;
import scrap.heap.refactor.dto.OrderDto;
import scrap.heap.refactor.manager.OrderManager;

public class OrderManagerTest {
	@Test
	public void testOrderManager() {
		OrderManager orderManager = new OrderManager();

		BalloonDto balloon = BalloonDto.builder().color("blue").material("latex").number("7").build();
		CakeDto cake = CakeDto.builder().flavor("Vanilla").frostingFlavor("chocolate").shape("square").size("med")
				.color("brown").build();
		OrderDto order = OrderDto.builder().cake(cake).balloon(balloon).build();

		assertTrue(orderManager.order(order));
	}

}
